### ISSUE TITLE
Determine how to handle order # generation.

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-core#1]
Currently, every entity has an `id` that is auto-incremented via Doctrine/MySQL.

Additionally we are exposing an `encoded id` in the View decorator:
https://github.com/inklabs/kommerce-core/blob/master/src/Entity/View/Order.php#L40

Note: The encodedId is used to hide raw id fields from the end user. This is typically done to protect the number of users or other entity that a company would rather hide from competitors. Btw, the encodeBase can be overridden via this class variable:
https://github.com/inklabs/kommerce-core/blob/master/src/Lib/BaseConvert.php#L6

Example:

```
$order->id = 3000
$order->encodedId = '2BC'
```

**Questions:**
Is this `encoded id` good enough to represent the order number?
Or should we come up with another way to represent order numbers?
Should we allow seeding the order number? This could be done by setting AUTO_INCREMENT in MySQL.

**Other Stores:**
Amazon: #107-9274342-8903026
Magento: #100000001
Open Cart: #971
Dolibarr Order: CO1310-0071
Dolibarr Invoice: FA1311-0071

**Comment by pdt256** [comment]
My main concern with an incrementing order # is that a competitor can deduce your annual run rate. This can be accomplished by purchasing a product from your store on the first day of each month/quarter and inspecting the numerical difference.

**Comment by bryan-maxwell** [comment]
I think masking it like this would be fine if you can guarantee no collisions. There's also libraries like this: https://github.com/ivanakimov/hashids.php that can do forward and backward conversion from a number using private key so it's not extractable.
