### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-core#106]
Add docker containers to support:
* nginx 1.10
* PHP 7.1 | php-fpm | opcache
* Percona Server 5.7 (MySQL)
* Redis 3.2.6

**Comment by jasonraimondi** [comment]
Do you think the docker container be a separate project under inklabs such as 'kommerce-docker' or should we put it on a branch in the kommerce-laravel project?

**Comment by pdt256** [comment]
The Docker configs will be closely related to the kommerce-laravel project. That seems like a good place for it right now.

We can migrate it to another project If it gets big, or someone wants to leverage the same containers and create a kommerce-wordpress or kommerce-symfony project.

**Comment by jasonraimondi** [comment]
Proposing the directory structure:

```
/kommerce-laravel
|-- application
|   |-- app
|   |-- bin
|   |-- bootstrap
|   |-- ...
|-- docker
|-- data
|-- logs
```

**Comment by pdt256** [comment]
Closed by https://github.com/inklabs/kommerce-laravel/commit/f94830db3e40d2669dea40bc409f8772d1d8cec2
