### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-core#107]
We need suggestions for a project name that we can brand for the open source project.

**Comment by pdt256** [comment]
Domains that are available:
CartVillage.com
CartThemes.com
BeachCommerce.com
MakerCommerce.com
CommunityStone.com
StoneTheme.com
StoneTemplates.com

**Comment by jasonraimondi** [comment]
Thinking less literally,

**Comment by jasonraimondi** [comment]
Thinking less literally, just spitballing here. Domain names aside, even though I am aware that is super important, we can make something work. 

Latin:
Fortuna - lucky
Solidum - solid
Mercatus - market
Carrum - cart
Tabernarius - shopkeeper
venditor - salesman

Random:
Market Square
Shopkeeper 
Emporium - a large retail store selling a wide variety of goods.


What about something related to the base Cardinal theme? Bird related or something.

**Comment by jasonraimondi** [comment]
We can have a name that doesnt mean anything. yahoo/google
We can have a name that has a background historical meaning. 
We can have a name that means something in a different language. latin/native american (cardinal)
We can have a literal name. cardinal
Compound words that are literal: open cart
Partial compound words that are still not literal like 'venmo', 'vend more'. 'costco'

**Comment by pdt256** [comment]
**Hawk** is a synonym to **sell** and relates to cardinal. Maybe something based on that?

These are available:
HawkLocal.com
HawkShopping.com
HawkFusion.com
HawkShops.com
HawkStores.com
HawkShip.com
HawkSell.com
UnHawk.com
LiquidHawk.com
PolyHawk.com
SolidHawk.com
PublicHawk.com
WorldwideHawk.com
MassHawk.com

**Comment by pdt256** [comment]
Hawk in native american languages:
Muscogee Creek - ayo
Cherokee - tawodi, tawadi, tawodiusdi, tlanuwa
Lakota Sioux - cetan
Navajo - ginítsoh, atseełtsoii, tsiyaalzhahí
Shawnee - kiakiak
Choctaw - biakak, hasimbish humma, shikkiliklik
Apache - Itza-chu, Liluye
Hopi - Palakwayo

**Comment by pdt256** [comment]
Kopen, buy in Dutch
Karte, coupon in German

**Comment by pdt256** [comment]
Available:
KopenShop.com 
KarteShop.com
KarteStore.com
Hawkopen.com
Ayohawk.com

**Comment by pdt256** [comment]
Finding a new name is exhausting. Finding a name in this domain without a collision is near impossible.

**Comment by jasonraimondi** [comment]
karteinc.com is available, I kind of like that.
kartemarket.com
kartebox.com
kartestore.com

**Comment by pdt256** [comment]
We can re-open this at a later time. For now we are **Zen Kommerce**. Project homepage will be hosted here: https://inklabs.github.io/kommerce-laravel/
