### ISSUE TITLE
PHP 7 Support and Roadmap

### ISSUE THREAD

**Issue by bryan-maxwell** [inklabs/kommerce-core#16]
We need to consider tagging the current release candidate as being supported up to PHP version 5.x and the PHP 7 version would be tagged accordingly. This way developers using older versions of PHP can still benefit from the core.

We will not offer support for the PHP 5.x supported release of core but it will still be available for forking, pull requests and use in the PHP community.

All further development will occur on the PHP7 tag and branches. This will allow us to roadmap features and PHP7 support to incentivize the switch for other developers and the community, but still allow them to work with the code in a familiar environment.

**Comment by pdt256** [comment]
This is a fair compromise. We are targeting a core release (v1.0) soon which requires PHP 5.6. The next major release (v2.0) can require PHP 7. That might happen in Q1 or Q2 next year.

**Comment by fulopattila122** [comment]
Just a side note, there's no PHP 6.x

;) cheers

**Comment by bryan-maxwell** [comment]
Fixed! I think it's a mental habit to have 6 before 7 :)

I like the idea that we'll release 1.0 with support up to 5.6 and future releases will be 7.x.

**Comment by pdt256** [comment]
Typed Properties in 7.1 would be a great addition to the EntityDTO objects.
https://wiki.php.net/rfc/typed-properties

``` php
class Foo {
  public int $int = 1;
  public float $flt = 2.2;
  public array $arr = [];
  public bool $bool = false;
  public string $string;
  public callable $callable;
  public stdClass $std;
  public OtherThing $other;
  public $mixed;
}
```

**Comment by pdt256** [comment]
We will require PHP 7.1 in the next release.

**Comment by pdt256** [comment]
unit tests now pass in PHP 7.1. 23971da2ecc6a0ed98346e6135cce5b4d8a09368

**Comment by pdt256** [comment]
Work is tracked on this branch: https://github.com/inklabs/kommerce-core/commits/php71

**Comment by pdt256** [comment]
PR is up: https://github.com/inklabs/kommerce-core/pull/112
