### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by bojanz** [inklabs/kommerce-core#3]
Hi, I'm a fellow ecommerce developer (Drupal Commerce).
Found a link to this project on Reddit, went through the code, it's a good start.

If you're interested in making your addressing/tax implementations more international, take a look at my two libraries and the linked blog posts:
https://github.com/commerceguys/addressing
https://github.com/commerceguys/tax
I've spent a lot of time researching these specific problems, would be happy to see the ideas stolen by as many projects as possible :)

Happy to discuss this and other topics in case you have questions or are wondering how we did things on our side.

**Comment by pdt256** [comment]
Thanks for the links and info.

Currently, we only have domestic US based customers using this project. This ticket may be re-opened in the future to account for international VAT/GST taxes.
