### ISSUE TITLE
User should be able to attach a file to an Order Item

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-core#35]
### User Account Orders
- [x] Attachments should be visible on each Order Item.
- [x] Allow User to upload multiple Attachments to an Order Item
- [x] Allow User to delete Attachments from an Order Item
### Anonymous Attachment Upload to Order
- [x] User should be able to share a secure URL with an Anonymous user to upload an attachment to their Cart Item or Order item.
  - This will enable someone to purchase gifts for multiple people where they could independently upload their files before or after checkout.

**Comment by bryan-maxwell** [comment]
A few thoughts:
- Should the CartItem pending UGC be marked in a certain status
- Should the CartItem be tied to a users email address so you need the link as well as the gifted persons email in order to fulfill/upload the pending content
- Does the customer complete the order and fill in shipping information, or could a customer be responsible just for an asset and nothing else?

**Comment by pdt256** [comment]
@tekhneek
1) yes, a Product or Tag should be able to determine whether the Attachment UGC upload is required prior to checkout.
2) yes. We need to tie 1+ email address to an Attachment so we can remind them to upload their files.
3) Uploading user will be responsible for uploading the asset and nothing else. Purchasing customer enters single shipping destination on checkout.

Currently we only support the customer to input a single shipping destination for a complete order. The Admin Panel supports multiple shipment parcels per order, but again, we currently support only a single destination. This will change to support multiple destinations in the future.

**Comment by pdt256** [comment]
The Attachment Entity might be a good opportunity to introduce UUIDs into the system. This would allow us to use the UUID in the URL for anonymous users to upload assets.

I'm not sure we need to build out secure token authentication to allow people to upload assets to an order. Once an order is complete, the Attachment will be locked and no longer accessible by anonymous users.

relates to #24

**Comment by pdt256** [comment]
As a customer, I purchase an OrderItem (with attachments enabled) and receive an email (with link to upload).
Additionally, I can print a physical coupon (with 4x4 code upload URL and QR code)
I can share the email and/or coupon with the gift recipient.
